/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author adrgimmun
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        mostrarReporte();
    }
    
    private void mostrarReporte() {
    try {
        // 1. Conexión (Asegúrate de que XAMPP esté encendido)
        Connection conn = DriverManager.getConnection(
            "jdbc:mariadb://localhost:3306/productos_bd", "root", "");
        
                java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery("SELECT * FROM productos");
        if (!rs.next()) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡ATENCIÓN! Java conectó bien, pero la tabla está VACÍA.");
        } else {
            System.out.println("¡ÉXITO! Java está leyendo datos. El primero es: " + rs.getString("nombre"));
        }

        // 2. Cargar el archivo .jasper desde la carpeta de recursos
        InputStream reporte = getClass().getResourceAsStream("/reports/reporte_productos.jasper");
        
        if (reporte == null) {
            throw new Exception("No se pudo encontrar el archivo .jasper");
        }

        // 3. Llenar el reporte con datos
        JasperPrint print = JasperFillManager.fillReport(reporte, null, conn);

        // 4. Mostrarlo en el visor de Jasper
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setTitle("Informe de Productos");
        viewer.setVisible(true);

        // 5. Cerrar esta ventana auxiliar
        this.dispose(); 
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
