/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.swing.JRViewer;
import java.awt.BorderLayout;
import java.sql.*;

/**
 *
 * @author adrgimmun
 */
public class FrmReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReportes.class.getName());

    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        mostrarReporte();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Informe");
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // La ventana se abre a pantalla completa
        this.setTitle("Visor de Productos - Sistema de Gestión");
        this.setLocationRelativeTo(null); // Centra la ventana si no está maximizada
    }
    
    private void mostrarReporte() {
        try {
            // 1. Establecer conexión
            Connection conn = DriverManager.getConnection(
                "jdbc:mariadb://localhost:3306/productos_bd", "root", "");

            // 2. Cargar el archivo compilado .jasper
            InputStream is = getClass().getResourceAsStream("/reports/reporte_productos.jasper");

            if (is == null) {
                throw new Exception("No se encontró el archivo .jasper. Revisa la carpeta resources.");
            }

            // 3. Llenar el reporte con los datos de la BD
            JasperPrint jp = JasperFillManager.fillReport(is, null, conn);

            if (jp.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay datos para mostrar en el informe.");
                this.dispose(); // Cerramos la ventana si está vacía
                return;
            }
            
            // 4. CREAR EL VISOR (JRViewer)
            // Esto crea el componente visual con barras de herramientas y zoom
            JRViewer viewer = new JRViewer(jp);

            // 5. INCRUSTAR EN EL PANEL
            pnlVisor.setLayout(new BorderLayout()); // Aseguramos que use BorderLayout
            pnlVisor.removeAll(); // Limpiamos cualquier rastro previo
            pnlVisor.add(viewer, BorderLayout.CENTER); // Añadimos el visor al centro

            // 6. REFRESCAR LA INTERFAZ
            // Sin esto, el panel podría quedarse gris hasta que redimensiones la ventana
            pnlVisor.revalidate();
            pnlVisor.repaint();

        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar reporte: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlVisor.setBackground(new java.awt.Color(239, 243, 243));

        javax.swing.GroupLayout pnlVisorLayout = new javax.swing.GroupLayout(pnlVisor);
        pnlVisor.setLayout(pnlVisorLayout);
        pnlVisorLayout.setHorizontalGroup(
            pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlVisorLayout.setVerticalGroup(
            pnlVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(pnlVisor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReportes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlVisor;
    // End of variables declaration//GEN-END:variables
}
